[book]
authors = ["Am0rfu5"]
language = "en"
multilingual = false
src = "src"
title = "The Web3 Security Book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
curly-quotes = true


[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding
